# BASE_DISTRIBUTION is used to switch between the old base distribution and distroless base images
ARG BASE_DISTRIBUTION=default

FROM istionightly/base_debug as default

FROM gcr.io/distroless/static as distroless

FROM ${BASE_DISTRIBUTION}
ADD node_agent_k8s /
ENTRYPOINT ["/node_agent_k8s"]
